from prometheus_client import Counter, Histogram

search_requests = Counter(
    "search_requests_total",
    "Total search requests",
    ["cached"],
)

search_latency = Histogram(
    "search_latency_seconds",
    "Search latency in seconds",
)

chat_requests = Counter(
    "chat_requests_total",
    "Total chat requests",
    ["cached"],
)

chat_latency = Histogram(
    "chat_latency_seconds",
    "End-to-end /chat latency in seconds",
)

prompt_tokens = Counter(
    "llm_prompt_tokens_total",
    "Total prompt tokens sent to the LLM",
)

completion_tokens = Counter(
    "llm_completion_tokens_total",
    "Total completion tokens generated by the LLM",
)

node_latency = Histogram(
    "graph_node_seconds",
    "Per-node agent graph latency in seconds",
    ["node"],
)

semantic_cache_hits = Counter(
    "semantic_cache_hits_total",
    "LLM semantic cache hits",
)

semantic_cache_misses = Counter(
    "semantic_cache_misses_total",
    "LLM semantic cache misses",
)
